version: "3"
services:
    dnd_discord_bot:
        network_mode: host
        build:
            context: ./
            dockerfile: "Dockerfile"
        volumes:
            - ..:/dnd_discord_bot
        ports:
            - "6543:6543"
        command: /bin/sh -c 'cd dnd_discord_bot && pip3 install discord.py && while sleep 1000; do :; done'

        

